django_tutorial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_app.urls')),
]

learning_app/urls.py
""" Defines URL patterns for learning_app."""
from django.urls import path
from . import views
# Use app_name to replace namespace
app_name = 'learning_app'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topics/<int:topic_id>/', views.topic, name='topic'),
]

learning_app/models.py
from django.db import models

# Create your models here.


class Topic(models.Model):
    """A topic the user is learning about"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text

class Entry(models.Model):
    """Something specific learned about a topic"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE,)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    class Meta:
        verbose_name_plural = 'entries'
    def __str__(self):
        """Return a string representation of the model."""
        return self.text[:50] + "..."

learning_app/views.py
from django.shortcuts import render
from django.template import loader
from .models import Topic

# Create your views here.
def index(request):
    """The home page for Learning Log"""
    return render(request, 'learning_app/index.html')

def topics(request):
    """Show all topics."""
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_app/topics.html', context)

def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_app/topic.html', context)

learning_app/templates/learning_app/base.html
<p>
    <a href="{% url 'learning_app:index' %}">Learning Log</a>
    <a href="{% url 'learning_app:topics' %}">Topics</a>
</p>

{% block content %}{% endblock content %}

learning_app/templates/learning_app/index.html
{% extends "learning_app/base.html" %}
{% block content %}
<p>Learning Log helps you keep track of your learning, for any topic
you're learning about.</p>
{% endblock content %}

learning_app/templates/learning_app/topic.html
{% extends 'learning_app/base.html' %}
{% block content %}
    <p>Topic: {{ topic }}</p>
    <p>Entries:</p>
    <ul>
        {% for entry in entries %}
            <li>
                <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
                <p>{{ entry.text|linebreaks }}</p>
            </li>
        {% empty %}
        <li>
            There are no entries for this topic yet.
        </li>
        {% endfor %}
    </ul>
{% endblock content %}

learning_app/templates/learning_app/topics.html
{% extends "learning_app/base.html" %}
{% block content %}
    <p>Topics</p>
    <ul>
        {% for topic in topics %}
            <li>
                <a href="{% url 'learning_app:topic' topic.id %}">{{ topic }}</a>
            </li>
        {% empty %}
            <li>No topics have been added yet.</li>
        {% endfor %}
    </ul>
{% endblock content %}